"""
Django settings for techbuilder project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import dj_database_url
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (explicit path) and override any existing env vars
load_dotenv(BASE_DIR / '.env', override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-&mu76@%ks51ct9szcx^#&bnnlsnbdafz=s21z8r(c5=7-+$(kq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,testserver').split(',')

# If running on Render, auto-allow the service hostname
# Render commonly exposes RENDER_EXTERNAL_HOSTNAME or RENDER_EXTERNAL_URL
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME') or os.getenv('RENDER_EXTERNAL_URL', '')
if _render_host:
    try:
        from urllib.parse import urlparse
        parsed = urlparse(_render_host)
        host = parsed.netloc or parsed.path or _render_host
        host = host.strip()
        if host and host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
    except Exception:
        # Best-effort: add raw value if parsing fails
        if _render_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #3rd party apps
    'rest_framework',
    'djoser',
    'django_filters',
    'corsheaders',
     
    #local apps
    'product',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'techbuilder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'techbuilder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Get database URL from environment variable
DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    # Use PostgreSQL from environment
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # Fallback to SQLite for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'productionfiles'

# WhiteNoise static files storage (Django 5+ STORAGES setting)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Base url to serve media files
MEDIA_URL = '/media/'

# Path where media is stored'
MEDIA_ROOT = BASE_DIR / 'media'

# Rest Framework settings

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

#djoser authentication settings
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),  # accept both header prefixes
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365)
}

DJOSER = {
    'LOGIN_FIELD': 'email',          # default; our custom view accepts username OR email
    'SEND_ACTIVATION_EMAIL': False,  # new users active immediately
    # For password reset emails: djoser will build a link as
    # {FRONTEND_ORIGIN}/{url}?uid={uid}&token={token}
    'PASSWORD_RESET_CONFIRM_URL': 'auth/reset-password-confirm?uid={uid}&token={token}',
}

# CORS settings for frontend connection
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]

# Add any additional frontend URLs from environment
if os.getenv('FRONTEND_URL'):
    CORS_ALLOWED_ORIGINS.append(os.getenv('FRONTEND_URL'))

CORS_ALLOW_CREDENTIALS = True
# Allow custom headers used by frontend/Stripe and expose auth for debugging
# NOTE: Using split('') on an empty env yields [''] which breaks CORS preflight.
# So only honor the env var if it contains at least one non-empty header value.
_raw_cors_headers = os.getenv('CORS_ALLOW_HEADERS', '').strip()
if _raw_cors_headers:
    CORS_ALLOW_HEADERS = [h.strip() for h in _raw_cors_headers.split(',') if h.strip()]
else:
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-language',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
        'stripe-signature',
    ]
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'
]
CORS_EXPOSE_HEADERS = ['authorization']
CORS_PREFLIGHT_MAX_AGE = 86400

# Stripe config (test mode supported). Set STRIPE_SECRET_KEY in your .env for checkout.
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
# Frontend origin for success/cancel URLs
FRONTEND_ORIGIN = os.getenv('FRONTEND_ORIGIN', 'http://127.0.0.1:3000')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Email configuration (console by default; override via .env for SMTP)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@techbuilder.local')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587')) if os.getenv('EMAIL_PORT') else None
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'

# Branding / site
SITE_NAME = os.getenv('SITE_NAME', 'TechBuilder')
SITE_DOMAIN = os.getenv('SITE_DOMAIN', 'localhost:8000')

# Logging to help debug auth, stock checks, and checkout
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django.request': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'rest_framework': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'corsheaders': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'product': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'core': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'stripe': {'level': 'DEBUG' if DEBUG else 'INFO', 'handlers': ['console'], 'propagate': False},
        'django.db.backends': {'level': 'WARNING', 'handlers': ['console'], 'propagate': False},
    },
}


